CREATE TABLE SEASONS (
    SEASON_ID INT AUTO_INCREMENT PRIMARY KEY,
    SEASON_YEAR YEAR UNIQUE,
);

--CREATE TABLE PLAYERS (
--    PLAYER_NAME UNIQUE PRIMARY KEY,
--    CURRENT_TEAM VARCHAR,
--    CURRENT_AGE BIGINT NOT NULL,
--    CURRENT_POS VARCHAR,
--);

CREATE TABLE PASSING_STATS (
    SEASON_RANK INTEGER PRIMARY KEY,
    TEAM VARCHAR,
    AGE INTEGER,
    POS VARCHAR,
    GAMES_PLAYED INTEGER,
    GAMES_STARTED INTEGER,
    COMPLETIONS INTEGER,
    ATTEMPTS INTEGER,
    COMPLETION_PERCENT DECIMAL,
    TOTAL_YARDS INTEGER,
    TOUCHDOWNS INTEGER,
    TOUCHDOWN_PERCENT DECIMAL,
    INTERCEPTIONS INTEGER,
    INTERCEPTION_PERCENT DECIMAL,
    FOREIGN KEY (SEASON_YEAR) references SEASONS(SEASON_YEAR)
--    FOREIGN KEY (PLAYER_NAME) references PLAYERS(PLAYER_NAME),
);
